# Generated by Django 4.2.6 on 2023-10-17 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='youtube',
            new_name='youtube_id',
        ),
    ]
